universe=docker
docker_image=hanyingj/pymc3-sklearn

executable=MCMC.sh
transfer_input_files=script.py, sum.py

# requesting resources
request_memory=100MB
request_cpus=1
request_disk=100MB

# parameters
environment="id=$(Step)"

# log files
error= /home/hjiang252/CHTC_test/ce4/res/err$(Process).err
output= /home/hjiang252/CHTC_test/ce4/res/out$(Process).out
log= /home/hjiang252/CHTC_test/ce4/res/log$(Process).log
queue 1
